defaults: &defaults
  docker:
    - image: circleci/node:10.20.0--browsers
      environment:
        JOBS: 1
  working_directory: ~/ember-cli-honeybadger-io

version: 2
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .

  install_dependencies:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - node-modules-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Yarn Install
          command: yarn install --non-interactive --pure-lockfile
      - save_cache:
          key: node-modules-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/ember-cli-honeybadger-io/node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint Handlebars
          command: yarn lint:hbs
      - run:
          name: Lint JavaScript
          command: yarn lint:js

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests
          command: npx ember try:one ember-default --skip-cleanup=true
      - store_test_results:
          path: test-results

  test_release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests Ember Release
          command: npx ember try:one ember-release --skip-cleanup=true
      - store_test_results:
          path: test-results

workflows:
  version: 2
  test_matrix:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - lint:
          requires:
            - install_dependencies
      - test:
          requires:
            - install_dependencies
      - test_release:
          requires:
            - install_dependencies
